version: "3.3"
services:
  db-tests:
    container_name: db-tests
    build:
      context: repository-jdbi
      dockerfile: ./tests/Dockerfile-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5432:5432